### ISSUE TITLE
首页直接报这个错

### ISSUE THREAD

**Issue by q707180869** [3tnet/tiny#7]
ErrorException (E_ERROR)
The Mix manifest does not exist. (View: E:\phpstudy\PHPTutorial\laravel5.5\tiny\resources\views\frontend\layouts\default.blade.php) (View: E:\phpstudy\PHPTutorial\laravel5.5\tiny\resources\views\frontend\layouts\default.blade.php)

**Comment by tw1997** [comment]
你前端安装了吗

**Comment by q707180869** [comment]
看views里面有些文件，就是npm的时候报了很多警告，
npm warn deprecated ...
好多这样的，难道问题出在这了

**Comment by q707180869** [comment]
今天试了一下npm，莫名其妙的又好了， 这后台登录密码是什么
